###
GET http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/getAuthenticationURL?state=abcd&redirect_uri=your_redirect_uri.com

###
GET https://us-central1-wallet-gpt-924f1.cloudfunctions.net/getTokensFromCode?code=<YOUR_CODE>&state=abcd
Content-Type: application/json

{
    "client_id": "YOUR_CLIENT_ID", 
    "client_secret": "YOUR_CLIENT_SECRET",
    "code": "YOUR_CODE"
}

###
POST http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/getTokensFromCode
Content-Type: application/json

{
    "client_id": "YOUR_CLIENT_ID", 
    "client_secret": "YOUR_CLIENT_SECRET",
    "refresh_token": "YOUR_REFRESH_TOKEN"
}

###
POST http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/addIncomeToWallet
Authorization: Bearer <YOUR TOKEN>
Content-Type: application/json

{
    "amount": 10,
    "description": "Pocket Money"
}


###
POST http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/addExpenseToWallet
Authorization: Bearer <YOUR TOKEN>
Content-Type: application/json

{
    "amount": 2.35,
    "description": "Lunch at Taco Bell"
}


###
POST http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/addExpenseToWallet
Authorization: Bearer <YOUR TOKEN>
Content-Type: application/json

{
    "amount": 5.25,
    "description": "Groceries at Walmart"
}

###
GET http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/resetWallet
Authorization: Bearer <YOUR TOKEN>

###
GET http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/getWalletBalance
Authorization: Bearer <YOUR TOKEN>

###
GET http://127.0.0.1:5001/wallet-gpt-924f1/us-central1/getLatestTransactions
Authorization: Bearer <YOUR TOKEN>